[settings]
odasrvpath = "/usr/local/bin/odasrv" # this is TERRIBLE for security, cause the service can just run any executable then
configdir = "/path/to/configs"
wadpaths = [
  "/path/to/wads",
  "/other/path/to/wads"
]
waddownloaddir = "/path/to/wads"

[servers]
server1 = { config = "example.cfg", port = 10666 }
